// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: deep_v2.proto

package probepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingEnum int32

const (
	PingEnum_PING_ENUM_INVALID PingEnum = 0
	PingEnum_PING_ENUM_PING    PingEnum = 1
	PingEnum_PING_ENUM_PONG    PingEnum = 2
)

// Enum value maps for PingEnum.
var (
	PingEnum_name = map[int32]string{
		0: "PING_ENUM_INVALID",
		1: "PING_ENUM_PING",
		2: "PING_ENUM_PONG",
	}
	PingEnum_value = map[string]int32{
		"PING_ENUM_INVALID": 0,
		"PING_ENUM_PING":    1,
		"PING_ENUM_PONG":    2,
	}
)

func (x PingEnum) Enum() *PingEnum {
	p := new(PingEnum)
	*p = x
	return p
}

func (x PingEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_deep_v2_proto_enumTypes[0].Descriptor()
}

func (PingEnum) Type() protoreflect.EnumType {
	return &file_deep_v2_proto_enumTypes[0]
}

func (x PingEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingEnum.Descriptor instead.
func (PingEnum) EnumDescriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{0}
}

type PongEnum int32

const (
	PongEnum_PONG_ENUM_INVALID PongEnum = 0
	PongEnum_PONG_ENUM_PING    PongEnum = 1
	PongEnum_PONG_ENUM_PONG    PongEnum = 2
)

// Enum value maps for PongEnum.
var (
	PongEnum_name = map[int32]string{
		0: "PONG_ENUM_INVALID",
		1: "PONG_ENUM_PING",
		2: "PONG_ENUM_PONG",
	}
	PongEnum_value = map[string]int32{
		"PONG_ENUM_INVALID": 0,
		"PONG_ENUM_PING":    1,
		"PONG_ENUM_PONG":    2,
	}
)

func (x PongEnum) Enum() *PongEnum {
	p := new(PongEnum)
	*p = x
	return p
}

func (x PongEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PongEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_deep_v2_proto_enumTypes[1].Descriptor()
}

func (PongEnum) Type() protoreflect.EnumType {
	return &file_deep_v2_proto_enumTypes[1]
}

func (x PongEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PongEnum.Descriptor instead.
func (PongEnum) EnumDescriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{1}
}

type EchoRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Payload                    *Ping                  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SleepBeforeCopy            *durationpb.Duration   `protobuf:"bytes,2,opt,name=sleep_before_copy,json=sleepBeforeCopy,proto3" json:"sleep_before_copy,omitempty"`
	SleepAfterCopy             *durationpb.Duration   `protobuf:"bytes,3,opt,name=sleep_after_copy,json=sleepAfterCopy,proto3" json:"sleep_after_copy,omitempty"`
	RespondWithError           bool                   `protobuf:"varint,4,opt,name=respond_with_error,json=respondWithError,proto3" json:"respond_with_error,omitempty"`
	ExpectedTransportHeaders   map[string]string      `protobuf:"bytes,5,rep,name=expected_transport_headers,json=expectedTransportHeaders,proto3" json:"expected_transport_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpectedApplicationHeaders map[string]string      `protobuf:"bytes,6,rep,name=expected_application_headers,json=expectedApplicationHeaders,proto3" json:"expected_application_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_deep_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetPayload() *Ping {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoRequest) GetSleepBeforeCopy() *durationpb.Duration {
	if x != nil {
		return x.SleepBeforeCopy
	}
	return nil
}

func (x *EchoRequest) GetSleepAfterCopy() *durationpb.Duration {
	if x != nil {
		return x.SleepAfterCopy
	}
	return nil
}

func (x *EchoRequest) GetRespondWithError() bool {
	if x != nil {
		return x.RespondWithError
	}
	return false
}

func (x *EchoRequest) GetExpectedTransportHeaders() map[string]string {
	if x != nil {
		return x.ExpectedTransportHeaders
	}
	return nil
}

func (x *EchoRequest) GetExpectedApplicationHeaders() map[string]string {
	if x != nil {
		return x.ExpectedApplicationHeaders
	}
	return nil
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *Pong                  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_deep_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetPayload() *Pong {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EchoErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *Pong                  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoErrorDetail) Reset() {
	*x = EchoErrorDetail{}
	mi := &file_deep_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoErrorDetail) ProtoMessage() {}

func (x *EchoErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoErrorDetail.ProtoReflect.Descriptor instead.
func (*EchoErrorDetail) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{2}
}

func (x *EchoErrorDetail) GetPayload() *Pong {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EchoAnyRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AnyWithWellknownField    *anypb.Any             `protobuf:"bytes,1,opt,name=any_with_wellknown_field,json=anyWithWellknownField,proto3" json:"any_with_wellknown_field,omitempty"`
	AnyWithEchoDurationField *anypb.Any             `protobuf:"bytes,2,opt,name=any_with_echo_duration_field,json=anyWithEchoDurationField,proto3" json:"any_with_echo_duration_field,omitempty"`
	AnyWithEchoIntField      *anypb.Any             `protobuf:"bytes,3,opt,name=any_with_echo_int_field,json=anyWithEchoIntField,proto3" json:"any_with_echo_int_field,omitempty"`
	AnyWithEchoNestedField   *anypb.Any             `protobuf:"bytes,4,opt,name=any_with_echo_nested_field,json=anyWithEchoNestedField,proto3" json:"any_with_echo_nested_field,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EchoAnyRequest) Reset() {
	*x = EchoAnyRequest{}
	mi := &file_deep_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoAnyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoAnyRequest) ProtoMessage() {}

func (x *EchoAnyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoAnyRequest.ProtoReflect.Descriptor instead.
func (*EchoAnyRequest) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{3}
}

func (x *EchoAnyRequest) GetAnyWithWellknownField() *anypb.Any {
	if x != nil {
		return x.AnyWithWellknownField
	}
	return nil
}

func (x *EchoAnyRequest) GetAnyWithEchoDurationField() *anypb.Any {
	if x != nil {
		return x.AnyWithEchoDurationField
	}
	return nil
}

func (x *EchoAnyRequest) GetAnyWithEchoIntField() *anypb.Any {
	if x != nil {
		return x.AnyWithEchoIntField
	}
	return nil
}

func (x *EchoAnyRequest) GetAnyWithEchoNestedField() *anypb.Any {
	if x != nil {
		return x.AnyWithEchoNestedField
	}
	return nil
}

type EchoDurationType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *durationpb.Duration   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoDurationType) Reset() {
	*x = EchoDurationType{}
	mi := &file_deep_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoDurationType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoDurationType) ProtoMessage() {}

func (x *EchoDurationType) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoDurationType.ProtoReflect.Descriptor instead.
func (*EchoDurationType) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{4}
}

func (x *EchoDurationType) GetField() *durationpb.Duration {
	if x != nil {
		return x.Field
	}
	return nil
}

type EchoIntType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         int32                  `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second        int64                  `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoIntType) Reset() {
	*x = EchoIntType{}
	mi := &file_deep_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoIntType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoIntType) ProtoMessage() {}

func (x *EchoIntType) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoIntType.ProtoReflect.Descriptor instead.
func (*EchoIntType) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{5}
}

func (x *EchoIntType) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *EchoIntType) GetSecond() int64 {
	if x != nil {
		return x.Second
	}
	return 0
}

type EchoNestedType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Nested        *EchoIntType           `protobuf:"bytes,2,opt,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoNestedType) Reset() {
	*x = EchoNestedType{}
	mi := &file_deep_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoNestedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoNestedType) ProtoMessage() {}

func (x *EchoNestedType) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoNestedType.ProtoReflect.Descriptor instead.
func (*EchoNestedType) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{6}
}

func (x *EchoNestedType) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *EchoNestedType) GetNested() *EchoIntType {
	if x != nil {
		return x.Nested
	}
	return nil
}

type EchoAnyResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AnyWithWellknownField    *anypb.Any             `protobuf:"bytes,5,opt,name=any_with_wellknown_field,json=anyWithWellknownField,proto3" json:"any_with_wellknown_field,omitempty"`
	AnyWithEchoDurationField *anypb.Any             `protobuf:"bytes,6,opt,name=any_with_echo_duration_field,json=anyWithEchoDurationField,proto3" json:"any_with_echo_duration_field,omitempty"`
	AnyWithEchoIntField      *anypb.Any             `protobuf:"bytes,7,opt,name=any_with_echo_int_field,json=anyWithEchoIntField,proto3" json:"any_with_echo_int_field,omitempty"`
	AnyWithEchoNestedField   *anypb.Any             `protobuf:"bytes,8,opt,name=any_with_echo_nested_field,json=anyWithEchoNestedField,proto3" json:"any_with_echo_nested_field,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EchoAnyResponse) Reset() {
	*x = EchoAnyResponse{}
	mi := &file_deep_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoAnyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoAnyResponse) ProtoMessage() {}

func (x *EchoAnyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoAnyResponse.ProtoReflect.Descriptor instead.
func (*EchoAnyResponse) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{7}
}

func (x *EchoAnyResponse) GetAnyWithWellknownField() *anypb.Any {
	if x != nil {
		return x.AnyWithWellknownField
	}
	return nil
}

func (x *EchoAnyResponse) GetAnyWithEchoDurationField() *anypb.Any {
	if x != nil {
		return x.AnyWithEchoDurationField
	}
	return nil
}

func (x *EchoAnyResponse) GetAnyWithEchoIntField() *anypb.Any {
	if x != nil {
		return x.AnyWithEchoIntField
	}
	return nil
}

func (x *EchoAnyResponse) GetAnyWithEchoNestedField() *anypb.Any {
	if x != nil {
		return x.AnyWithEchoNestedField
	}
	return nil
}

type EchoStreamRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Payload                    *Ping                  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SleepBeforeCopy            *durationpb.Duration   `protobuf:"bytes,2,opt,name=sleep_before_copy,json=sleepBeforeCopy,proto3" json:"sleep_before_copy,omitempty"`
	SleepAfterCopy             *durationpb.Duration   `protobuf:"bytes,3,opt,name=sleep_after_copy,json=sleepAfterCopy,proto3" json:"sleep_after_copy,omitempty"`
	RespondWithError           bool                   `protobuf:"varint,4,opt,name=respond_with_error,json=respondWithError,proto3" json:"respond_with_error,omitempty"`
	ExpectedTransportHeaders   map[string]string      `protobuf:"bytes,5,rep,name=expected_transport_headers,json=expectedTransportHeaders,proto3" json:"expected_transport_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpectedApplicationHeaders map[string]string      `protobuf:"bytes,6,rep,name=expected_application_headers,json=expectedApplicationHeaders,proto3" json:"expected_application_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *EchoStreamRequest) Reset() {
	*x = EchoStreamRequest{}
	mi := &file_deep_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoStreamRequest) ProtoMessage() {}

func (x *EchoStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoStreamRequest.ProtoReflect.Descriptor instead.
func (*EchoStreamRequest) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{8}
}

func (x *EchoStreamRequest) GetPayload() *Ping {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoStreamRequest) GetSleepBeforeCopy() *durationpb.Duration {
	if x != nil {
		return x.SleepBeforeCopy
	}
	return nil
}

func (x *EchoStreamRequest) GetSleepAfterCopy() *durationpb.Duration {
	if x != nil {
		return x.SleepAfterCopy
	}
	return nil
}

func (x *EchoStreamRequest) GetRespondWithError() bool {
	if x != nil {
		return x.RespondWithError
	}
	return false
}

func (x *EchoStreamRequest) GetExpectedTransportHeaders() map[string]string {
	if x != nil {
		return x.ExpectedTransportHeaders
	}
	return nil
}

func (x *EchoStreamRequest) GetExpectedApplicationHeaders() map[string]string {
	if x != nil {
		return x.ExpectedApplicationHeaders
	}
	return nil
}

type EchoStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *Pong                  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoStreamResponse) Reset() {
	*x = EchoStreamResponse{}
	mi := &file_deep_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoStreamResponse) ProtoMessage() {}

func (x *EchoStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoStreamResponse.ProtoReflect.Descriptor instead.
func (*EchoStreamResponse) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{9}
}

func (x *EchoStreamResponse) GetPayload() *Pong {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ping struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PingInt32    int32                  `protobuf:"varint,1,opt,name=ping_int32,json=pingInt32,proto3" json:"ping_int32,omitempty"`
	PingInt64    int64                  `protobuf:"varint,2,opt,name=ping_int64,json=pingInt64,proto3" json:"ping_int64,omitempty"`
	PingUint32   uint32                 `protobuf:"varint,3,opt,name=ping_uint32,json=pingUint32,proto3" json:"ping_uint32,omitempty"`
	PingUint64   uint64                 `protobuf:"varint,4,opt,name=ping_uint64,json=pingUint64,proto3" json:"ping_uint64,omitempty"`
	PingSint32   int32                  `protobuf:"zigzag32,5,opt,name=ping_sint32,json=pingSint32,proto3" json:"ping_sint32,omitempty"`
	PingSint64   int64                  `protobuf:"zigzag64,6,opt,name=ping_sint64,json=pingSint64,proto3" json:"ping_sint64,omitempty"`
	PingFixed32  uint32                 `protobuf:"fixed32,7,opt,name=ping_fixed32,json=pingFixed32,proto3" json:"ping_fixed32,omitempty"`
	PingFixed64  uint64                 `protobuf:"fixed64,8,opt,name=ping_fixed64,json=pingFixed64,proto3" json:"ping_fixed64,omitempty"`
	PingSfixed32 int32                  `protobuf:"fixed32,9,opt,name=ping_sfixed32,json=pingSfixed32,proto3" json:"ping_sfixed32,omitempty"`
	PingSfixed64 int64                  `protobuf:"fixed64,10,opt,name=ping_sfixed64,json=pingSfixed64,proto3" json:"ping_sfixed64,omitempty"`
	PingBool     bool                   `protobuf:"varint,11,opt,name=ping_bool,json=pingBool,proto3" json:"ping_bool,omitempty"`
	PingString   string                 `protobuf:"bytes,12,opt,name=ping_string,json=pingString,proto3" json:"ping_string,omitempty"`
	PingBytes    []byte                 `protobuf:"bytes,13,opt,name=ping_bytes,json=pingBytes,proto3" json:"ping_bytes,omitempty"`
	PingFloat    float32                `protobuf:"fixed32,14,opt,name=ping_float,json=pingFloat,proto3" json:"ping_float,omitempty"`
	PingDouble   float64                `protobuf:"fixed64,15,opt,name=ping_double,json=pingDouble,proto3" json:"ping_double,omitempty"`
	PingList     []*Ping                `protobuf:"bytes,16,rep,name=ping_list,json=pingList,proto3" json:"ping_list,omitempty"`
	PingMap      map[string]*Ping       `protobuf:"bytes,17,rep,name=ping_map,json=pingMap,proto3" json:"ping_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to PingOneOf:
	//
	//	*Ping_PingOneOfString
	//	*Ping_PingOneOfBool
	PingOneOf     isPing_PingOneOf `protobuf_oneof:"ping_one_of"`
	PingEnum      PingEnum         `protobuf:"varint,20,opt,name=ping_enum,json=pingEnum,proto3,enum=uber.infra.net.rpc.probe.PingEnum" json:"ping_enum,omitempty"`
	PingMessage   *Ping            `protobuf:"bytes,21,opt,name=ping_message,json=pingMessage,proto3" json:"ping_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_deep_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{10}
}

func (x *Ping) GetPingInt32() int32 {
	if x != nil {
		return x.PingInt32
	}
	return 0
}

func (x *Ping) GetPingInt64() int64 {
	if x != nil {
		return x.PingInt64
	}
	return 0
}

func (x *Ping) GetPingUint32() uint32 {
	if x != nil {
		return x.PingUint32
	}
	return 0
}

func (x *Ping) GetPingUint64() uint64 {
	if x != nil {
		return x.PingUint64
	}
	return 0
}

func (x *Ping) GetPingSint32() int32 {
	if x != nil {
		return x.PingSint32
	}
	return 0
}

func (x *Ping) GetPingSint64() int64 {
	if x != nil {
		return x.PingSint64
	}
	return 0
}

func (x *Ping) GetPingFixed32() uint32 {
	if x != nil {
		return x.PingFixed32
	}
	return 0
}

func (x *Ping) GetPingFixed64() uint64 {
	if x != nil {
		return x.PingFixed64
	}
	return 0
}

func (x *Ping) GetPingSfixed32() int32 {
	if x != nil {
		return x.PingSfixed32
	}
	return 0
}

func (x *Ping) GetPingSfixed64() int64 {
	if x != nil {
		return x.PingSfixed64
	}
	return 0
}

func (x *Ping) GetPingBool() bool {
	if x != nil {
		return x.PingBool
	}
	return false
}

func (x *Ping) GetPingString() string {
	if x != nil {
		return x.PingString
	}
	return ""
}

func (x *Ping) GetPingBytes() []byte {
	if x != nil {
		return x.PingBytes
	}
	return nil
}

func (x *Ping) GetPingFloat() float32 {
	if x != nil {
		return x.PingFloat
	}
	return 0
}

func (x *Ping) GetPingDouble() float64 {
	if x != nil {
		return x.PingDouble
	}
	return 0
}

func (x *Ping) GetPingList() []*Ping {
	if x != nil {
		return x.PingList
	}
	return nil
}

func (x *Ping) GetPingMap() map[string]*Ping {
	if x != nil {
		return x.PingMap
	}
	return nil
}

func (x *Ping) GetPingOneOf() isPing_PingOneOf {
	if x != nil {
		return x.PingOneOf
	}
	return nil
}

func (x *Ping) GetPingOneOfString() string {
	if x != nil {
		if x, ok := x.PingOneOf.(*Ping_PingOneOfString); ok {
			return x.PingOneOfString
		}
	}
	return ""
}

func (x *Ping) GetPingOneOfBool() bool {
	if x != nil {
		if x, ok := x.PingOneOf.(*Ping_PingOneOfBool); ok {
			return x.PingOneOfBool
		}
	}
	return false
}

func (x *Ping) GetPingEnum() PingEnum {
	if x != nil {
		return x.PingEnum
	}
	return PingEnum_PING_ENUM_INVALID
}

func (x *Ping) GetPingMessage() *Ping {
	if x != nil {
		return x.PingMessage
	}
	return nil
}

type isPing_PingOneOf interface {
	isPing_PingOneOf()
}

type Ping_PingOneOfString struct {
	PingOneOfString string `protobuf:"bytes,18,opt,name=ping_one_of_string,json=pingOneOfString,proto3,oneof"`
}

type Ping_PingOneOfBool struct {
	PingOneOfBool bool `protobuf:"varint,19,opt,name=ping_one_of_bool,json=pingOneOfBool,proto3,oneof"`
}

func (*Ping_PingOneOfString) isPing_PingOneOf() {}

func (*Ping_PingOneOfBool) isPing_PingOneOf() {}

type Pong struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PongInt32    int32                  `protobuf:"varint,1,opt,name=pong_int32,json=pongInt32,proto3" json:"pong_int32,omitempty"`
	PongInt64    int64                  `protobuf:"varint,2,opt,name=pong_int64,json=pongInt64,proto3" json:"pong_int64,omitempty"`
	PongUint32   uint32                 `protobuf:"varint,3,opt,name=pong_uint32,json=pongUint32,proto3" json:"pong_uint32,omitempty"`
	PongUint64   uint64                 `protobuf:"varint,4,opt,name=pong_uint64,json=pongUint64,proto3" json:"pong_uint64,omitempty"`
	PongSint32   int32                  `protobuf:"zigzag32,5,opt,name=pong_sint32,json=pongSint32,proto3" json:"pong_sint32,omitempty"`
	PongSint64   int64                  `protobuf:"zigzag64,6,opt,name=pong_sint64,json=pongSint64,proto3" json:"pong_sint64,omitempty"`
	PongFixed32  uint32                 `protobuf:"fixed32,7,opt,name=pong_fixed32,json=pongFixed32,proto3" json:"pong_fixed32,omitempty"`
	PongFixed64  uint64                 `protobuf:"fixed64,8,opt,name=pong_fixed64,json=pongFixed64,proto3" json:"pong_fixed64,omitempty"`
	PongSfixed32 int32                  `protobuf:"fixed32,9,opt,name=pong_sfixed32,json=pongSfixed32,proto3" json:"pong_sfixed32,omitempty"`
	PongSfixed64 int64                  `protobuf:"fixed64,10,opt,name=pong_sfixed64,json=pongSfixed64,proto3" json:"pong_sfixed64,omitempty"`
	PongBool     bool                   `protobuf:"varint,11,opt,name=pong_bool,json=pongBool,proto3" json:"pong_bool,omitempty"`
	PongString   string                 `protobuf:"bytes,12,opt,name=pong_string,json=pongString,proto3" json:"pong_string,omitempty"`
	PongBytes    []byte                 `protobuf:"bytes,13,opt,name=pong_bytes,json=pongBytes,proto3" json:"pong_bytes,omitempty"`
	PongFloat    float32                `protobuf:"fixed32,14,opt,name=pong_float,json=pongFloat,proto3" json:"pong_float,omitempty"`
	PongDouble   float64                `protobuf:"fixed64,15,opt,name=pong_double,json=pongDouble,proto3" json:"pong_double,omitempty"`
	PongList     []*Pong                `protobuf:"bytes,16,rep,name=pong_list,json=pongList,proto3" json:"pong_list,omitempty"`
	PongMap      map[string]*Pong       `protobuf:"bytes,17,rep,name=pong_map,json=pongMap,proto3" json:"pong_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to PongOneOf:
	//
	//	*Pong_PongOneOfString
	//	*Pong_PongOneOfBool
	PongOneOf     isPong_PongOneOf `protobuf_oneof:"pong_one_of"`
	PongEnum      PongEnum         `protobuf:"varint,20,opt,name=pong_enum,json=pongEnum,proto3,enum=uber.infra.net.rpc.probe.PongEnum" json:"pong_enum,omitempty"`
	PongMessage   *Pong            `protobuf:"bytes,21,opt,name=pong_message,json=pongMessage,proto3" json:"pong_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_deep_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_deep_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_deep_v2_proto_rawDescGZIP(), []int{11}
}

func (x *Pong) GetPongInt32() int32 {
	if x != nil {
		return x.PongInt32
	}
	return 0
}

func (x *Pong) GetPongInt64() int64 {
	if x != nil {
		return x.PongInt64
	}
	return 0
}

func (x *Pong) GetPongUint32() uint32 {
	if x != nil {
		return x.PongUint32
	}
	return 0
}

func (x *Pong) GetPongUint64() uint64 {
	if x != nil {
		return x.PongUint64
	}
	return 0
}

func (x *Pong) GetPongSint32() int32 {
	if x != nil {
		return x.PongSint32
	}
	return 0
}

func (x *Pong) GetPongSint64() int64 {
	if x != nil {
		return x.PongSint64
	}
	return 0
}

func (x *Pong) GetPongFixed32() uint32 {
	if x != nil {
		return x.PongFixed32
	}
	return 0
}

func (x *Pong) GetPongFixed64() uint64 {
	if x != nil {
		return x.PongFixed64
	}
	return 0
}

func (x *Pong) GetPongSfixed32() int32 {
	if x != nil {
		return x.PongSfixed32
	}
	return 0
}

func (x *Pong) GetPongSfixed64() int64 {
	if x != nil {
		return x.PongSfixed64
	}
	return 0
}

func (x *Pong) GetPongBool() bool {
	if x != nil {
		return x.PongBool
	}
	return false
}

func (x *Pong) GetPongString() string {
	if x != nil {
		return x.PongString
	}
	return ""
}

func (x *Pong) GetPongBytes() []byte {
	if x != nil {
		return x.PongBytes
	}
	return nil
}

func (x *Pong) GetPongFloat() float32 {
	if x != nil {
		return x.PongFloat
	}
	return 0
}

func (x *Pong) GetPongDouble() float64 {
	if x != nil {
		return x.PongDouble
	}
	return 0
}

func (x *Pong) GetPongList() []*Pong {
	if x != nil {
		return x.PongList
	}
	return nil
}

func (x *Pong) GetPongMap() map[string]*Pong {
	if x != nil {
		return x.PongMap
	}
	return nil
}

func (x *Pong) GetPongOneOf() isPong_PongOneOf {
	if x != nil {
		return x.PongOneOf
	}
	return nil
}

func (x *Pong) GetPongOneOfString() string {
	if x != nil {
		if x, ok := x.PongOneOf.(*Pong_PongOneOfString); ok {
			return x.PongOneOfString
		}
	}
	return ""
}

func (x *Pong) GetPongOneOfBool() bool {
	if x != nil {
		if x, ok := x.PongOneOf.(*Pong_PongOneOfBool); ok {
			return x.PongOneOfBool
		}
	}
	return false
}

func (x *Pong) GetPongEnum() PongEnum {
	if x != nil {
		return x.PongEnum
	}
	return PongEnum_PONG_ENUM_INVALID
}

func (x *Pong) GetPongMessage() *Pong {
	if x != nil {
		return x.PongMessage
	}
	return nil
}

type isPong_PongOneOf interface {
	isPong_PongOneOf()
}

type Pong_PongOneOfString struct {
	PongOneOfString string `protobuf:"bytes,18,opt,name=pong_one_of_string,json=pongOneOfString,proto3,oneof"`
}

type Pong_PongOneOfBool struct {
	PongOneOfBool bool `protobuf:"varint,19,opt,name=pong_one_of_bool,json=pongOneOfBool,proto3,oneof"`
}

func (*Pong_PongOneOfString) isPong_PongOneOf() {}

func (*Pong_PongOneOfBool) isPong_PongOneOf() {}

var File_deep_v2_proto protoreflect.FileDescriptor

const file_deep_v2_proto_rawDesc = "" +
	"\n" +
	"\rdeep_v2.proto\x12\x18uber.infra.net.rpc.probe\x1a\x1egoogle/protobuf/duration.proto\x1a\x19google/protobuf/any.proto\"\xab\x05\n" +
	"\vEchoRequest\x128\n" +
	"\apayload\x18\x01 \x01(\v2\x1e.uber.infra.net.rpc.probe.PingR\apayload\x12E\n" +
	"\x11sleep_before_copy\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fsleepBeforeCopy\x12C\n" +
	"\x10sleep_after_copy\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0esleepAfterCopy\x12,\n" +
	"\x12respond_with_error\x18\x04 \x01(\bR\x10respondWithError\x12\x81\x01\n" +
	"\x1aexpected_transport_headers\x18\x05 \x03(\v2C.uber.infra.net.rpc.probe.EchoRequest.ExpectedTransportHeadersEntryR\x18expectedTransportHeaders\x12\x87\x01\n" +
	"\x1cexpected_application_headers\x18\x06 \x03(\v2E.uber.infra.net.rpc.probe.EchoRequest.ExpectedApplicationHeadersEntryR\x1aexpectedApplicationHeaders\x1aK\n" +
	"\x1dExpectedTransportHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aM\n" +
	"\x1fExpectedApplicationHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\fEchoResponse\x128\n" +
	"\apayload\x18\x01 \x01(\v2\x1e.uber.infra.net.rpc.probe.PongR\apayload\"K\n" +
	"\x0fEchoErrorDetail\x128\n" +
	"\apayload\x18\x01 \x01(\v2\x1e.uber.infra.net.rpc.probe.PongR\apayload\"\xd3\x02\n" +
	"\x0eEchoAnyRequest\x12M\n" +
	"\x18any_with_wellknown_field\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x15anyWithWellknownField\x12T\n" +
	"\x1cany_with_echo_duration_field\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x18anyWithEchoDurationField\x12J\n" +
	"\x17any_with_echo_int_field\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x13anyWithEchoIntField\x12P\n" +
	"\x1aany_with_echo_nested_field\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x16anyWithEchoNestedField\"C\n" +
	"\x10EchoDurationType\x12/\n" +
	"\x05field\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05field\";\n" +
	"\vEchoIntType\x12\x14\n" +
	"\x05first\x18\x01 \x01(\x05R\x05first\x12\x16\n" +
	"\x06second\x18\x02 \x01(\x03R\x06second\"i\n" +
	"\x0eEchoNestedType\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12=\n" +
	"\x06nested\x18\x02 \x01(\v2%.uber.infra.net.rpc.probe.EchoIntTypeR\x06nested\"\xd4\x02\n" +
	"\x0fEchoAnyResponse\x12M\n" +
	"\x18any_with_wellknown_field\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x15anyWithWellknownField\x12T\n" +
	"\x1cany_with_echo_duration_field\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\x18anyWithEchoDurationField\x12J\n" +
	"\x17any_with_echo_int_field\x18\a \x01(\v2\x14.google.protobuf.AnyR\x13anyWithEchoIntField\x12P\n" +
	"\x1aany_with_echo_nested_field\x18\b \x01(\v2\x14.google.protobuf.AnyR\x16anyWithEchoNestedField\"\xbd\x05\n" +
	"\x11EchoStreamRequest\x128\n" +
	"\apayload\x18\x01 \x01(\v2\x1e.uber.infra.net.rpc.probe.PingR\apayload\x12E\n" +
	"\x11sleep_before_copy\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fsleepBeforeCopy\x12C\n" +
	"\x10sleep_after_copy\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0esleepAfterCopy\x12,\n" +
	"\x12respond_with_error\x18\x04 \x01(\bR\x10respondWithError\x12\x87\x01\n" +
	"\x1aexpected_transport_headers\x18\x05 \x03(\v2I.uber.infra.net.rpc.probe.EchoStreamRequest.ExpectedTransportHeadersEntryR\x18expectedTransportHeaders\x12\x8d\x01\n" +
	"\x1cexpected_application_headers\x18\x06 \x03(\v2K.uber.infra.net.rpc.probe.EchoStreamRequest.ExpectedApplicationHeadersEntryR\x1aexpectedApplicationHeaders\x1aK\n" +
	"\x1dExpectedTransportHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aM\n" +
	"\x1fExpectedApplicationHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x12EchoStreamResponse\x128\n" +
	"\apayload\x18\x01 \x01(\v2\x1e.uber.infra.net.rpc.probe.PongR\apayload\"\xc3\a\n" +
	"\x04Ping\x12\x1d\n" +
	"\n" +
	"ping_int32\x18\x01 \x01(\x05R\tpingInt32\x12\x1d\n" +
	"\n" +
	"ping_int64\x18\x02 \x01(\x03R\tpingInt64\x12\x1f\n" +
	"\vping_uint32\x18\x03 \x01(\rR\n" +
	"pingUint32\x12\x1f\n" +
	"\vping_uint64\x18\x04 \x01(\x04R\n" +
	"pingUint64\x12\x1f\n" +
	"\vping_sint32\x18\x05 \x01(\x11R\n" +
	"pingSint32\x12\x1f\n" +
	"\vping_sint64\x18\x06 \x01(\x12R\n" +
	"pingSint64\x12!\n" +
	"\fping_fixed32\x18\a \x01(\aR\vpingFixed32\x12!\n" +
	"\fping_fixed64\x18\b \x01(\x06R\vpingFixed64\x12#\n" +
	"\rping_sfixed32\x18\t \x01(\x0fR\fpingSfixed32\x12#\n" +
	"\rping_sfixed64\x18\n" +
	" \x01(\x10R\fpingSfixed64\x12\x1b\n" +
	"\tping_bool\x18\v \x01(\bR\bpingBool\x12\x1f\n" +
	"\vping_string\x18\f \x01(\tR\n" +
	"pingString\x12\x1d\n" +
	"\n" +
	"ping_bytes\x18\r \x01(\fR\tpingBytes\x12\x1d\n" +
	"\n" +
	"ping_float\x18\x0e \x01(\x02R\tpingFloat\x12\x1f\n" +
	"\vping_double\x18\x0f \x01(\x01R\n" +
	"pingDouble\x12;\n" +
	"\tping_list\x18\x10 \x03(\v2\x1e.uber.infra.net.rpc.probe.PingR\bpingList\x12F\n" +
	"\bping_map\x18\x11 \x03(\v2+.uber.infra.net.rpc.probe.Ping.PingMapEntryR\apingMap\x12-\n" +
	"\x12ping_one_of_string\x18\x12 \x01(\tH\x00R\x0fpingOneOfString\x12)\n" +
	"\x10ping_one_of_bool\x18\x13 \x01(\bH\x00R\rpingOneOfBool\x12?\n" +
	"\tping_enum\x18\x14 \x01(\x0e2\".uber.infra.net.rpc.probe.PingEnumR\bpingEnum\x12A\n" +
	"\fping_message\x18\x15 \x01(\v2\x1e.uber.infra.net.rpc.probe.PingR\vpingMessage\x1aZ\n" +
	"\fPingMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.uber.infra.net.rpc.probe.PingR\x05value:\x028\x01B\r\n" +
	"\vping_one_of\"\xc3\a\n" +
	"\x04Pong\x12\x1d\n" +
	"\n" +
	"pong_int32\x18\x01 \x01(\x05R\tpongInt32\x12\x1d\n" +
	"\n" +
	"pong_int64\x18\x02 \x01(\x03R\tpongInt64\x12\x1f\n" +
	"\vpong_uint32\x18\x03 \x01(\rR\n" +
	"pongUint32\x12\x1f\n" +
	"\vpong_uint64\x18\x04 \x01(\x04R\n" +
	"pongUint64\x12\x1f\n" +
	"\vpong_sint32\x18\x05 \x01(\x11R\n" +
	"pongSint32\x12\x1f\n" +
	"\vpong_sint64\x18\x06 \x01(\x12R\n" +
	"pongSint64\x12!\n" +
	"\fpong_fixed32\x18\a \x01(\aR\vpongFixed32\x12!\n" +
	"\fpong_fixed64\x18\b \x01(\x06R\vpongFixed64\x12#\n" +
	"\rpong_sfixed32\x18\t \x01(\x0fR\fpongSfixed32\x12#\n" +
	"\rpong_sfixed64\x18\n" +
	" \x01(\x10R\fpongSfixed64\x12\x1b\n" +
	"\tpong_bool\x18\v \x01(\bR\bpongBool\x12\x1f\n" +
	"\vpong_string\x18\f \x01(\tR\n" +
	"pongString\x12\x1d\n" +
	"\n" +
	"pong_bytes\x18\r \x01(\fR\tpongBytes\x12\x1d\n" +
	"\n" +
	"pong_float\x18\x0e \x01(\x02R\tpongFloat\x12\x1f\n" +
	"\vpong_double\x18\x0f \x01(\x01R\n" +
	"pongDouble\x12;\n" +
	"\tpong_list\x18\x10 \x03(\v2\x1e.uber.infra.net.rpc.probe.PongR\bpongList\x12F\n" +
	"\bpong_map\x18\x11 \x03(\v2+.uber.infra.net.rpc.probe.Pong.PongMapEntryR\apongMap\x12-\n" +
	"\x12pong_one_of_string\x18\x12 \x01(\tH\x00R\x0fpongOneOfString\x12)\n" +
	"\x10pong_one_of_bool\x18\x13 \x01(\bH\x00R\rpongOneOfBool\x12?\n" +
	"\tpong_enum\x18\x14 \x01(\x0e2\".uber.infra.net.rpc.probe.PongEnumR\bpongEnum\x12A\n" +
	"\fpong_message\x18\x15 \x01(\v2\x1e.uber.infra.net.rpc.probe.PongR\vpongMessage\x1aZ\n" +
	"\fPongMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.uber.infra.net.rpc.probe.PongR\x05value:\x028\x01B\r\n" +
	"\vpong_one_of*I\n" +
	"\bPingEnum\x12\x15\n" +
	"\x11PING_ENUM_INVALID\x10\x00\x12\x12\n" +
	"\x0ePING_ENUM_PING\x10\x01\x12\x12\n" +
	"\x0ePING_ENUM_PONG\x10\x02*I\n" +
	"\bPongEnum\x12\x15\n" +
	"\x11PONG_ENUM_INVALID\x10\x00\x12\x12\n" +
	"\x0ePONG_ENUM_PING\x10\x01\x12\x12\n" +
	"\x0ePONG_ENUM_PONG\x10\x022\xb1\x02\n" +
	"\x05Probe\x12W\n" +
	"\x04Echo\x12%.uber.infra.net.rpc.probe.EchoRequest\x1a&.uber.infra.net.rpc.probe.EchoResponse\"\x00\x12`\n" +
	"\aEchoAny\x12(.uber.infra.net.rpc.probe.EchoAnyRequest\x1a).uber.infra.net.rpc.probe.EchoAnyResponse\"\x00\x12m\n" +
	"\n" +
	"EchoStream\x12+.uber.infra.net.rpc.probe.EchoStreamRequest\x1a,.uber.infra.net.rpc.probe.EchoStreamResponse\"\x00(\x010\x01Bl\n" +
	"\x1ccom.uber.infra.net.rpc.probeB\n" +
	"ProbeProtoP\x01Z>go.uber.org/yarpc/encoding/protobuf/internal/testpb/v2/probepbb\x06proto3"

var (
	file_deep_v2_proto_rawDescOnce sync.Once
	file_deep_v2_proto_rawDescData []byte
)

func file_deep_v2_proto_rawDescGZIP() []byte {
	file_deep_v2_proto_rawDescOnce.Do(func() {
		file_deep_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deep_v2_proto_rawDesc), len(file_deep_v2_proto_rawDesc)))
	})
	return file_deep_v2_proto_rawDescData
}

var file_deep_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_deep_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_deep_v2_proto_goTypes = []any{
	(PingEnum)(0),               // 0: uber.infra.net.rpc.probe.PingEnum
	(PongEnum)(0),               // 1: uber.infra.net.rpc.probe.PongEnum
	(*EchoRequest)(nil),         // 2: uber.infra.net.rpc.probe.EchoRequest
	(*EchoResponse)(nil),        // 3: uber.infra.net.rpc.probe.EchoResponse
	(*EchoErrorDetail)(nil),     // 4: uber.infra.net.rpc.probe.EchoErrorDetail
	(*EchoAnyRequest)(nil),      // 5: uber.infra.net.rpc.probe.EchoAnyRequest
	(*EchoDurationType)(nil),    // 6: uber.infra.net.rpc.probe.EchoDurationType
	(*EchoIntType)(nil),         // 7: uber.infra.net.rpc.probe.EchoIntType
	(*EchoNestedType)(nil),      // 8: uber.infra.net.rpc.probe.EchoNestedType
	(*EchoAnyResponse)(nil),     // 9: uber.infra.net.rpc.probe.EchoAnyResponse
	(*EchoStreamRequest)(nil),   // 10: uber.infra.net.rpc.probe.EchoStreamRequest
	(*EchoStreamResponse)(nil),  // 11: uber.infra.net.rpc.probe.EchoStreamResponse
	(*Ping)(nil),                // 12: uber.infra.net.rpc.probe.Ping
	(*Pong)(nil),                // 13: uber.infra.net.rpc.probe.Pong
	nil,                         // 14: uber.infra.net.rpc.probe.EchoRequest.ExpectedTransportHeadersEntry
	nil,                         // 15: uber.infra.net.rpc.probe.EchoRequest.ExpectedApplicationHeadersEntry
	nil,                         // 16: uber.infra.net.rpc.probe.EchoStreamRequest.ExpectedTransportHeadersEntry
	nil,                         // 17: uber.infra.net.rpc.probe.EchoStreamRequest.ExpectedApplicationHeadersEntry
	nil,                         // 18: uber.infra.net.rpc.probe.Ping.PingMapEntry
	nil,                         // 19: uber.infra.net.rpc.probe.Pong.PongMapEntry
	(*durationpb.Duration)(nil), // 20: google.protobuf.Duration
	(*anypb.Any)(nil),           // 21: google.protobuf.Any
}
var file_deep_v2_proto_depIdxs = []int32{
	12, // 0: uber.infra.net.rpc.probe.EchoRequest.payload:type_name -> uber.infra.net.rpc.probe.Ping
	20, // 1: uber.infra.net.rpc.probe.EchoRequest.sleep_before_copy:type_name -> google.protobuf.Duration
	20, // 2: uber.infra.net.rpc.probe.EchoRequest.sleep_after_copy:type_name -> google.protobuf.Duration
	14, // 3: uber.infra.net.rpc.probe.EchoRequest.expected_transport_headers:type_name -> uber.infra.net.rpc.probe.EchoRequest.ExpectedTransportHeadersEntry
	15, // 4: uber.infra.net.rpc.probe.EchoRequest.expected_application_headers:type_name -> uber.infra.net.rpc.probe.EchoRequest.ExpectedApplicationHeadersEntry
	13, // 5: uber.infra.net.rpc.probe.EchoResponse.payload:type_name -> uber.infra.net.rpc.probe.Pong
	13, // 6: uber.infra.net.rpc.probe.EchoErrorDetail.payload:type_name -> uber.infra.net.rpc.probe.Pong
	21, // 7: uber.infra.net.rpc.probe.EchoAnyRequest.any_with_wellknown_field:type_name -> google.protobuf.Any
	21, // 8: uber.infra.net.rpc.probe.EchoAnyRequest.any_with_echo_duration_field:type_name -> google.protobuf.Any
	21, // 9: uber.infra.net.rpc.probe.EchoAnyRequest.any_with_echo_int_field:type_name -> google.protobuf.Any
	21, // 10: uber.infra.net.rpc.probe.EchoAnyRequest.any_with_echo_nested_field:type_name -> google.protobuf.Any
	20, // 11: uber.infra.net.rpc.probe.EchoDurationType.field:type_name -> google.protobuf.Duration
	7,  // 12: uber.infra.net.rpc.probe.EchoNestedType.nested:type_name -> uber.infra.net.rpc.probe.EchoIntType
	21, // 13: uber.infra.net.rpc.probe.EchoAnyResponse.any_with_wellknown_field:type_name -> google.protobuf.Any
	21, // 14: uber.infra.net.rpc.probe.EchoAnyResponse.any_with_echo_duration_field:type_name -> google.protobuf.Any
	21, // 15: uber.infra.net.rpc.probe.EchoAnyResponse.any_with_echo_int_field:type_name -> google.protobuf.Any
	21, // 16: uber.infra.net.rpc.probe.EchoAnyResponse.any_with_echo_nested_field:type_name -> google.protobuf.Any
	12, // 17: uber.infra.net.rpc.probe.EchoStreamRequest.payload:type_name -> uber.infra.net.rpc.probe.Ping
	20, // 18: uber.infra.net.rpc.probe.EchoStreamRequest.sleep_before_copy:type_name -> google.protobuf.Duration
	20, // 19: uber.infra.net.rpc.probe.EchoStreamRequest.sleep_after_copy:type_name -> google.protobuf.Duration
	16, // 20: uber.infra.net.rpc.probe.EchoStreamRequest.expected_transport_headers:type_name -> uber.infra.net.rpc.probe.EchoStreamRequest.ExpectedTransportHeadersEntry
	17, // 21: uber.infra.net.rpc.probe.EchoStreamRequest.expected_application_headers:type_name -> uber.infra.net.rpc.probe.EchoStreamRequest.ExpectedApplicationHeadersEntry
	13, // 22: uber.infra.net.rpc.probe.EchoStreamResponse.payload:type_name -> uber.infra.net.rpc.probe.Pong
	12, // 23: uber.infra.net.rpc.probe.Ping.ping_list:type_name -> uber.infra.net.rpc.probe.Ping
	18, // 24: uber.infra.net.rpc.probe.Ping.ping_map:type_name -> uber.infra.net.rpc.probe.Ping.PingMapEntry
	0,  // 25: uber.infra.net.rpc.probe.Ping.ping_enum:type_name -> uber.infra.net.rpc.probe.PingEnum
	12, // 26: uber.infra.net.rpc.probe.Ping.ping_message:type_name -> uber.infra.net.rpc.probe.Ping
	13, // 27: uber.infra.net.rpc.probe.Pong.pong_list:type_name -> uber.infra.net.rpc.probe.Pong
	19, // 28: uber.infra.net.rpc.probe.Pong.pong_map:type_name -> uber.infra.net.rpc.probe.Pong.PongMapEntry
	1,  // 29: uber.infra.net.rpc.probe.Pong.pong_enum:type_name -> uber.infra.net.rpc.probe.PongEnum
	13, // 30: uber.infra.net.rpc.probe.Pong.pong_message:type_name -> uber.infra.net.rpc.probe.Pong
	12, // 31: uber.infra.net.rpc.probe.Ping.PingMapEntry.value:type_name -> uber.infra.net.rpc.probe.Ping
	13, // 32: uber.infra.net.rpc.probe.Pong.PongMapEntry.value:type_name -> uber.infra.net.rpc.probe.Pong
	2,  // 33: uber.infra.net.rpc.probe.Probe.Echo:input_type -> uber.infra.net.rpc.probe.EchoRequest
	5,  // 34: uber.infra.net.rpc.probe.Probe.EchoAny:input_type -> uber.infra.net.rpc.probe.EchoAnyRequest
	10, // 35: uber.infra.net.rpc.probe.Probe.EchoStream:input_type -> uber.infra.net.rpc.probe.EchoStreamRequest
	3,  // 36: uber.infra.net.rpc.probe.Probe.Echo:output_type -> uber.infra.net.rpc.probe.EchoResponse
	9,  // 37: uber.infra.net.rpc.probe.Probe.EchoAny:output_type -> uber.infra.net.rpc.probe.EchoAnyResponse
	11, // 38: uber.infra.net.rpc.probe.Probe.EchoStream:output_type -> uber.infra.net.rpc.probe.EchoStreamResponse
	36, // [36:39] is the sub-list for method output_type
	33, // [33:36] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_deep_v2_proto_init() }
func file_deep_v2_proto_init() {
	if File_deep_v2_proto != nil {
		return
	}
	file_deep_v2_proto_msgTypes[10].OneofWrappers = []any{
		(*Ping_PingOneOfString)(nil),
		(*Ping_PingOneOfBool)(nil),
	}
	file_deep_v2_proto_msgTypes[11].OneofWrappers = []any{
		(*Pong_PongOneOfString)(nil),
		(*Pong_PongOneOfBool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deep_v2_proto_rawDesc), len(file_deep_v2_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deep_v2_proto_goTypes,
		DependencyIndexes: file_deep_v2_proto_depIdxs,
		EnumInfos:         file_deep_v2_proto_enumTypes,
		MessageInfos:      file_deep_v2_proto_msgTypes,
	}.Build()
	File_deep_v2_proto = out.File
	file_deep_v2_proto_goTypes = nil
	file_deep_v2_proto_depIdxs = nil
}
