// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: deep_gogo.proto

package probepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PingEnum int32

const (
	PingEnum_PING_ENUM_INVALID PingEnum = 0
	PingEnum_PING_ENUM_PING    PingEnum = 1
	PingEnum_PING_ENUM_PONG    PingEnum = 2
)

var PingEnum_name = map[int32]string{
	0: "PING_ENUM_INVALID",
	1: "PING_ENUM_PING",
	2: "PING_ENUM_PONG",
}

var PingEnum_value = map[string]int32{
	"PING_ENUM_INVALID": 0,
	"PING_ENUM_PING":    1,
	"PING_ENUM_PONG":    2,
}

func (x PingEnum) String() string {
	return proto.EnumName(PingEnum_name, int32(x))
}

func (PingEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{0}
}

type PongEnum int32

const (
	PongEnum_PONG_ENUM_INVALID PongEnum = 0
	PongEnum_PONG_ENUM_PING    PongEnum = 1
	PongEnum_PONG_ENUM_PONG    PongEnum = 2
)

var PongEnum_name = map[int32]string{
	0: "PONG_ENUM_INVALID",
	1: "PONG_ENUM_PING",
	2: "PONG_ENUM_PONG",
}

var PongEnum_value = map[string]int32{
	"PONG_ENUM_INVALID": 0,
	"PONG_ENUM_PING":    1,
	"PONG_ENUM_PONG":    2,
}

func (x PongEnum) String() string {
	return proto.EnumName(PongEnum_name, int32(x))
}

func (PongEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{1}
}

type EchoRequest struct {
	Payload                    *Ping                `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SleepBeforeCopy            *durationpb.Duration `protobuf:"bytes,2,opt,name=sleep_before_copy,json=sleepBeforeCopy,proto3" json:"sleep_before_copy,omitempty"`
	SleepAfterCopy             *durationpb.Duration `protobuf:"bytes,3,opt,name=sleep_after_copy,json=sleepAfterCopy,proto3" json:"sleep_after_copy,omitempty"`
	RespondWithError           bool                 `protobuf:"varint,4,opt,name=respond_with_error,json=respondWithError,proto3" json:"respond_with_error,omitempty"`
	ExpectedTransportHeaders   map[string]string    `protobuf:"bytes,5,rep,name=expected_transport_headers,json=expectedTransportHeaders,proto3" json:"expected_transport_headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ExpectedApplicationHeaders map[string]string    `protobuf:"bytes,6,rep,name=expected_application_headers,json=expectedApplicationHeaders,proto3" json:"expected_application_headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral       struct{}             `json:"-"`
	XXX_unrecognized           []byte               `json:"-"`
	XXX_sizecache              int32                `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{0}
}
func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetPayload() *Ping {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *EchoRequest) GetSleepBeforeCopy() *durationpb.Duration {
	if m != nil {
		return m.SleepBeforeCopy
	}
	return nil
}

func (m *EchoRequest) GetSleepAfterCopy() *durationpb.Duration {
	if m != nil {
		return m.SleepAfterCopy
	}
	return nil
}

func (m *EchoRequest) GetRespondWithError() bool {
	if m != nil {
		return m.RespondWithError
	}
	return false
}

func (m *EchoRequest) GetExpectedTransportHeaders() map[string]string {
	if m != nil {
		return m.ExpectedTransportHeaders
	}
	return nil
}

func (m *EchoRequest) GetExpectedApplicationHeaders() map[string]string {
	if m != nil {
		return m.ExpectedApplicationHeaders
	}
	return nil
}

type EchoResponse struct {
	Payload              *Pong    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{1}
}
func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetPayload() *Pong {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EchoErrorDetail struct {
	Payload              *Pong    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoErrorDetail) Reset()         { *m = EchoErrorDetail{} }
func (m *EchoErrorDetail) String() string { return proto.CompactTextString(m) }
func (*EchoErrorDetail) ProtoMessage()    {}
func (*EchoErrorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{2}
}
func (m *EchoErrorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoErrorDetail.Unmarshal(m, b)
}
func (m *EchoErrorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoErrorDetail.Marshal(b, m, deterministic)
}
func (m *EchoErrorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoErrorDetail.Merge(m, src)
}
func (m *EchoErrorDetail) XXX_Size() int {
	return xxx_messageInfo_EchoErrorDetail.Size(m)
}
func (m *EchoErrorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoErrorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_EchoErrorDetail proto.InternalMessageInfo

func (m *EchoErrorDetail) GetPayload() *Pong {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EchoAnyRequest struct {
	AnyWithWellknownField    *anypb.Any `protobuf:"bytes,1,opt,name=any_with_wellknown_field,json=anyWithWellknownField,proto3" json:"any_with_wellknown_field,omitempty"`
	AnyWithEchoDurationField *anypb.Any `protobuf:"bytes,2,opt,name=any_with_echo_duration_field,json=anyWithEchoDurationField,proto3" json:"any_with_echo_duration_field,omitempty"`
	AnyWithEchoIntField      *anypb.Any `protobuf:"bytes,3,opt,name=any_with_echo_int_field,json=anyWithEchoIntField,proto3" json:"any_with_echo_int_field,omitempty"`
	AnyWithEchoNestedField   *anypb.Any `protobuf:"bytes,4,opt,name=any_with_echo_nested_field,json=anyWithEchoNestedField,proto3" json:"any_with_echo_nested_field,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}   `json:"-"`
	XXX_unrecognized         []byte     `json:"-"`
	XXX_sizecache            int32      `json:"-"`
}

func (m *EchoAnyRequest) Reset()         { *m = EchoAnyRequest{} }
func (m *EchoAnyRequest) String() string { return proto.CompactTextString(m) }
func (*EchoAnyRequest) ProtoMessage()    {}
func (*EchoAnyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{3}
}
func (m *EchoAnyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoAnyRequest.Unmarshal(m, b)
}
func (m *EchoAnyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoAnyRequest.Marshal(b, m, deterministic)
}
func (m *EchoAnyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoAnyRequest.Merge(m, src)
}
func (m *EchoAnyRequest) XXX_Size() int {
	return xxx_messageInfo_EchoAnyRequest.Size(m)
}
func (m *EchoAnyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoAnyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoAnyRequest proto.InternalMessageInfo

func (m *EchoAnyRequest) GetAnyWithWellknownField() *anypb.Any {
	if m != nil {
		return m.AnyWithWellknownField
	}
	return nil
}

func (m *EchoAnyRequest) GetAnyWithEchoDurationField() *anypb.Any {
	if m != nil {
		return m.AnyWithEchoDurationField
	}
	return nil
}

func (m *EchoAnyRequest) GetAnyWithEchoIntField() *anypb.Any {
	if m != nil {
		return m.AnyWithEchoIntField
	}
	return nil
}

func (m *EchoAnyRequest) GetAnyWithEchoNestedField() *anypb.Any {
	if m != nil {
		return m.AnyWithEchoNestedField
	}
	return nil
}

type EchoDurationType struct {
	Field                *durationpb.Duration `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EchoDurationType) Reset()         { *m = EchoDurationType{} }
func (m *EchoDurationType) String() string { return proto.CompactTextString(m) }
func (*EchoDurationType) ProtoMessage()    {}
func (*EchoDurationType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{4}
}
func (m *EchoDurationType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoDurationType.Unmarshal(m, b)
}
func (m *EchoDurationType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoDurationType.Marshal(b, m, deterministic)
}
func (m *EchoDurationType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoDurationType.Merge(m, src)
}
func (m *EchoDurationType) XXX_Size() int {
	return xxx_messageInfo_EchoDurationType.Size(m)
}
func (m *EchoDurationType) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoDurationType.DiscardUnknown(m)
}

var xxx_messageInfo_EchoDurationType proto.InternalMessageInfo

func (m *EchoDurationType) GetField() *durationpb.Duration {
	if m != nil {
		return m.Field
	}
	return nil
}

type EchoIntType struct {
	First                int32    `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second               int64    `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoIntType) Reset()         { *m = EchoIntType{} }
func (m *EchoIntType) String() string { return proto.CompactTextString(m) }
func (*EchoIntType) ProtoMessage()    {}
func (*EchoIntType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{5}
}
func (m *EchoIntType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoIntType.Unmarshal(m, b)
}
func (m *EchoIntType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoIntType.Marshal(b, m, deterministic)
}
func (m *EchoIntType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoIntType.Merge(m, src)
}
func (m *EchoIntType) XXX_Size() int {
	return xxx_messageInfo_EchoIntType.Size(m)
}
func (m *EchoIntType) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoIntType.DiscardUnknown(m)
}

var xxx_messageInfo_EchoIntType proto.InternalMessageInfo

func (m *EchoIntType) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *EchoIntType) GetSecond() int64 {
	if m != nil {
		return m.Second
	}
	return 0
}

type EchoNestedType struct {
	Payload              string       `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Nested               *EchoIntType `protobuf:"bytes,2,opt,name=nested,proto3" json:"nested,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EchoNestedType) Reset()         { *m = EchoNestedType{} }
func (m *EchoNestedType) String() string { return proto.CompactTextString(m) }
func (*EchoNestedType) ProtoMessage()    {}
func (*EchoNestedType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{6}
}
func (m *EchoNestedType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoNestedType.Unmarshal(m, b)
}
func (m *EchoNestedType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoNestedType.Marshal(b, m, deterministic)
}
func (m *EchoNestedType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoNestedType.Merge(m, src)
}
func (m *EchoNestedType) XXX_Size() int {
	return xxx_messageInfo_EchoNestedType.Size(m)
}
func (m *EchoNestedType) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoNestedType.DiscardUnknown(m)
}

var xxx_messageInfo_EchoNestedType proto.InternalMessageInfo

func (m *EchoNestedType) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *EchoNestedType) GetNested() *EchoIntType {
	if m != nil {
		return m.Nested
	}
	return nil
}

type EchoAnyResponse struct {
	AnyWithWellknownField    *anypb.Any `protobuf:"bytes,5,opt,name=any_with_wellknown_field,json=anyWithWellknownField,proto3" json:"any_with_wellknown_field,omitempty"`
	AnyWithEchoDurationField *anypb.Any `protobuf:"bytes,6,opt,name=any_with_echo_duration_field,json=anyWithEchoDurationField,proto3" json:"any_with_echo_duration_field,omitempty"`
	AnyWithEchoIntField      *anypb.Any `protobuf:"bytes,7,opt,name=any_with_echo_int_field,json=anyWithEchoIntField,proto3" json:"any_with_echo_int_field,omitempty"`
	AnyWithEchoNestedField   *anypb.Any `protobuf:"bytes,8,opt,name=any_with_echo_nested_field,json=anyWithEchoNestedField,proto3" json:"any_with_echo_nested_field,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}   `json:"-"`
	XXX_unrecognized         []byte     `json:"-"`
	XXX_sizecache            int32      `json:"-"`
}

func (m *EchoAnyResponse) Reset()         { *m = EchoAnyResponse{} }
func (m *EchoAnyResponse) String() string { return proto.CompactTextString(m) }
func (*EchoAnyResponse) ProtoMessage()    {}
func (*EchoAnyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{7}
}
func (m *EchoAnyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoAnyResponse.Unmarshal(m, b)
}
func (m *EchoAnyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoAnyResponse.Marshal(b, m, deterministic)
}
func (m *EchoAnyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoAnyResponse.Merge(m, src)
}
func (m *EchoAnyResponse) XXX_Size() int {
	return xxx_messageInfo_EchoAnyResponse.Size(m)
}
func (m *EchoAnyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoAnyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoAnyResponse proto.InternalMessageInfo

func (m *EchoAnyResponse) GetAnyWithWellknownField() *anypb.Any {
	if m != nil {
		return m.AnyWithWellknownField
	}
	return nil
}

func (m *EchoAnyResponse) GetAnyWithEchoDurationField() *anypb.Any {
	if m != nil {
		return m.AnyWithEchoDurationField
	}
	return nil
}

func (m *EchoAnyResponse) GetAnyWithEchoIntField() *anypb.Any {
	if m != nil {
		return m.AnyWithEchoIntField
	}
	return nil
}

func (m *EchoAnyResponse) GetAnyWithEchoNestedField() *anypb.Any {
	if m != nil {
		return m.AnyWithEchoNestedField
	}
	return nil
}

type EchoStreamRequest struct {
	Payload                    *Ping                `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SleepBeforeCopy            *durationpb.Duration `protobuf:"bytes,2,opt,name=sleep_before_copy,json=sleepBeforeCopy,proto3" json:"sleep_before_copy,omitempty"`
	SleepAfterCopy             *durationpb.Duration `protobuf:"bytes,3,opt,name=sleep_after_copy,json=sleepAfterCopy,proto3" json:"sleep_after_copy,omitempty"`
	RespondWithError           bool                 `protobuf:"varint,4,opt,name=respond_with_error,json=respondWithError,proto3" json:"respond_with_error,omitempty"`
	ExpectedTransportHeaders   map[string]string    `protobuf:"bytes,5,rep,name=expected_transport_headers,json=expectedTransportHeaders,proto3" json:"expected_transport_headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ExpectedApplicationHeaders map[string]string    `protobuf:"bytes,6,rep,name=expected_application_headers,json=expectedApplicationHeaders,proto3" json:"expected_application_headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral       struct{}             `json:"-"`
	XXX_unrecognized           []byte               `json:"-"`
	XXX_sizecache              int32                `json:"-"`
}

func (m *EchoStreamRequest) Reset()         { *m = EchoStreamRequest{} }
func (m *EchoStreamRequest) String() string { return proto.CompactTextString(m) }
func (*EchoStreamRequest) ProtoMessage()    {}
func (*EchoStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{8}
}
func (m *EchoStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoStreamRequest.Unmarshal(m, b)
}
func (m *EchoStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoStreamRequest.Marshal(b, m, deterministic)
}
func (m *EchoStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoStreamRequest.Merge(m, src)
}
func (m *EchoStreamRequest) XXX_Size() int {
	return xxx_messageInfo_EchoStreamRequest.Size(m)
}
func (m *EchoStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoStreamRequest proto.InternalMessageInfo

func (m *EchoStreamRequest) GetPayload() *Ping {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *EchoStreamRequest) GetSleepBeforeCopy() *durationpb.Duration {
	if m != nil {
		return m.SleepBeforeCopy
	}
	return nil
}

func (m *EchoStreamRequest) GetSleepAfterCopy() *durationpb.Duration {
	if m != nil {
		return m.SleepAfterCopy
	}
	return nil
}

func (m *EchoStreamRequest) GetRespondWithError() bool {
	if m != nil {
		return m.RespondWithError
	}
	return false
}

func (m *EchoStreamRequest) GetExpectedTransportHeaders() map[string]string {
	if m != nil {
		return m.ExpectedTransportHeaders
	}
	return nil
}

func (m *EchoStreamRequest) GetExpectedApplicationHeaders() map[string]string {
	if m != nil {
		return m.ExpectedApplicationHeaders
	}
	return nil
}

type EchoStreamResponse struct {
	Payload              *Pong    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoStreamResponse) Reset()         { *m = EchoStreamResponse{} }
func (m *EchoStreamResponse) String() string { return proto.CompactTextString(m) }
func (*EchoStreamResponse) ProtoMessage()    {}
func (*EchoStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{9}
}
func (m *EchoStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoStreamResponse.Unmarshal(m, b)
}
func (m *EchoStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoStreamResponse.Marshal(b, m, deterministic)
}
func (m *EchoStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoStreamResponse.Merge(m, src)
}
func (m *EchoStreamResponse) XXX_Size() int {
	return xxx_messageInfo_EchoStreamResponse.Size(m)
}
func (m *EchoStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoStreamResponse proto.InternalMessageInfo

func (m *EchoStreamResponse) GetPayload() *Pong {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Ping struct {
	PingInt32    int32            `protobuf:"varint,1,opt,name=ping_int32,json=pingInt32,proto3" json:"ping_int32,omitempty"`
	PingInt64    int64            `protobuf:"varint,2,opt,name=ping_int64,json=pingInt64,proto3" json:"ping_int64,omitempty"`
	PingUint32   uint32           `protobuf:"varint,3,opt,name=ping_uint32,json=pingUint32,proto3" json:"ping_uint32,omitempty"`
	PingUint64   uint64           `protobuf:"varint,4,opt,name=ping_uint64,json=pingUint64,proto3" json:"ping_uint64,omitempty"`
	PingSint32   int32            `protobuf:"zigzag32,5,opt,name=ping_sint32,json=pingSint32,proto3" json:"ping_sint32,omitempty"`
	PingSint64   int64            `protobuf:"zigzag64,6,opt,name=ping_sint64,json=pingSint64,proto3" json:"ping_sint64,omitempty"`
	PingFixed32  uint32           `protobuf:"fixed32,7,opt,name=ping_fixed32,json=pingFixed32,proto3" json:"ping_fixed32,omitempty"`
	PingFixed64  uint64           `protobuf:"fixed64,8,opt,name=ping_fixed64,json=pingFixed64,proto3" json:"ping_fixed64,omitempty"`
	PingSfixed32 int32            `protobuf:"fixed32,9,opt,name=ping_sfixed32,json=pingSfixed32,proto3" json:"ping_sfixed32,omitempty"`
	PingSfixed64 int64            `protobuf:"fixed64,10,opt,name=ping_sfixed64,json=pingSfixed64,proto3" json:"ping_sfixed64,omitempty"`
	PingBool     bool             `protobuf:"varint,11,opt,name=ping_bool,json=pingBool,proto3" json:"ping_bool,omitempty"`
	PingString   string           `protobuf:"bytes,12,opt,name=ping_string,json=pingString,proto3" json:"ping_string,omitempty"`
	PingBytes    []byte           `protobuf:"bytes,13,opt,name=ping_bytes,json=pingBytes,proto3" json:"ping_bytes,omitempty"`
	PingFloat    float32          `protobuf:"fixed32,14,opt,name=ping_float,json=pingFloat,proto3" json:"ping_float,omitempty"`
	PingDouble   float64          `protobuf:"fixed64,15,opt,name=ping_double,json=pingDouble,proto3" json:"ping_double,omitempty"`
	PingList     []*Ping          `protobuf:"bytes,16,rep,name=ping_list,json=pingList,proto3" json:"ping_list,omitempty"`
	PingMap      map[string]*Ping `protobuf:"bytes,17,rep,name=ping_map,json=pingMap,proto3" json:"ping_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are valid to be assigned to PingOneOf:
	//
	//	*Ping_PingOneOfString
	//	*Ping_PingOneOfBool
	PingOneOf            isPing_PingOneOf `protobuf_oneof:"ping_one_of"`
	PingEnum             PingEnum         `protobuf:"varint,20,opt,name=ping_enum,json=pingEnum,proto3,enum=uber.infra.net.rpc.probe.PingEnum" json:"ping_enum,omitempty"`
	PingMessage          *Ping            `protobuf:"bytes,21,opt,name=ping_message,json=pingMessage,proto3" json:"ping_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{10}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type isPing_PingOneOf interface {
	isPing_PingOneOf()
}

type Ping_PingOneOfString struct {
	PingOneOfString string `protobuf:"bytes,18,opt,name=ping_one_of_string,json=pingOneOfString,proto3,oneof" json:"ping_one_of_string,omitempty"`
}
type Ping_PingOneOfBool struct {
	PingOneOfBool bool `protobuf:"varint,19,opt,name=ping_one_of_bool,json=pingOneOfBool,proto3,oneof" json:"ping_one_of_bool,omitempty"`
}

func (*Ping_PingOneOfString) isPing_PingOneOf() {}
func (*Ping_PingOneOfBool) isPing_PingOneOf()   {}

func (m *Ping) GetPingOneOf() isPing_PingOneOf {
	if m != nil {
		return m.PingOneOf
	}
	return nil
}

func (m *Ping) GetPingInt32() int32 {
	if m != nil {
		return m.PingInt32
	}
	return 0
}

func (m *Ping) GetPingInt64() int64 {
	if m != nil {
		return m.PingInt64
	}
	return 0
}

func (m *Ping) GetPingUint32() uint32 {
	if m != nil {
		return m.PingUint32
	}
	return 0
}

func (m *Ping) GetPingUint64() uint64 {
	if m != nil {
		return m.PingUint64
	}
	return 0
}

func (m *Ping) GetPingSint32() int32 {
	if m != nil {
		return m.PingSint32
	}
	return 0
}

func (m *Ping) GetPingSint64() int64 {
	if m != nil {
		return m.PingSint64
	}
	return 0
}

func (m *Ping) GetPingFixed32() uint32 {
	if m != nil {
		return m.PingFixed32
	}
	return 0
}

func (m *Ping) GetPingFixed64() uint64 {
	if m != nil {
		return m.PingFixed64
	}
	return 0
}

func (m *Ping) GetPingSfixed32() int32 {
	if m != nil {
		return m.PingSfixed32
	}
	return 0
}

func (m *Ping) GetPingSfixed64() int64 {
	if m != nil {
		return m.PingSfixed64
	}
	return 0
}

func (m *Ping) GetPingBool() bool {
	if m != nil {
		return m.PingBool
	}
	return false
}

func (m *Ping) GetPingString() string {
	if m != nil {
		return m.PingString
	}
	return ""
}

func (m *Ping) GetPingBytes() []byte {
	if m != nil {
		return m.PingBytes
	}
	return nil
}

func (m *Ping) GetPingFloat() float32 {
	if m != nil {
		return m.PingFloat
	}
	return 0
}

func (m *Ping) GetPingDouble() float64 {
	if m != nil {
		return m.PingDouble
	}
	return 0
}

func (m *Ping) GetPingList() []*Ping {
	if m != nil {
		return m.PingList
	}
	return nil
}

func (m *Ping) GetPingMap() map[string]*Ping {
	if m != nil {
		return m.PingMap
	}
	return nil
}

func (m *Ping) GetPingOneOfString() string {
	if x, ok := m.GetPingOneOf().(*Ping_PingOneOfString); ok {
		return x.PingOneOfString
	}
	return ""
}

func (m *Ping) GetPingOneOfBool() bool {
	if x, ok := m.GetPingOneOf().(*Ping_PingOneOfBool); ok {
		return x.PingOneOfBool
	}
	return false
}

func (m *Ping) GetPingEnum() PingEnum {
	if m != nil {
		return m.PingEnum
	}
	return PingEnum_PING_ENUM_INVALID
}

func (m *Ping) GetPingMessage() *Ping {
	if m != nil {
		return m.PingMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Ping) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Ping_PingOneOfString)(nil),
		(*Ping_PingOneOfBool)(nil),
	}
}

type Pong struct {
	PongInt32    int32            `protobuf:"varint,1,opt,name=pong_int32,json=pongInt32,proto3" json:"pong_int32,omitempty"`
	PongInt64    int64            `protobuf:"varint,2,opt,name=pong_int64,json=pongInt64,proto3" json:"pong_int64,omitempty"`
	PongUint32   uint32           `protobuf:"varint,3,opt,name=pong_uint32,json=pongUint32,proto3" json:"pong_uint32,omitempty"`
	PongUint64   uint64           `protobuf:"varint,4,opt,name=pong_uint64,json=pongUint64,proto3" json:"pong_uint64,omitempty"`
	PongSint32   int32            `protobuf:"zigzag32,5,opt,name=pong_sint32,json=pongSint32,proto3" json:"pong_sint32,omitempty"`
	PongSint64   int64            `protobuf:"zigzag64,6,opt,name=pong_sint64,json=pongSint64,proto3" json:"pong_sint64,omitempty"`
	PongFixed32  uint32           `protobuf:"fixed32,7,opt,name=pong_fixed32,json=pongFixed32,proto3" json:"pong_fixed32,omitempty"`
	PongFixed64  uint64           `protobuf:"fixed64,8,opt,name=pong_fixed64,json=pongFixed64,proto3" json:"pong_fixed64,omitempty"`
	PongSfixed32 int32            `protobuf:"fixed32,9,opt,name=pong_sfixed32,json=pongSfixed32,proto3" json:"pong_sfixed32,omitempty"`
	PongSfixed64 int64            `protobuf:"fixed64,10,opt,name=pong_sfixed64,json=pongSfixed64,proto3" json:"pong_sfixed64,omitempty"`
	PongBool     bool             `protobuf:"varint,11,opt,name=pong_bool,json=pongBool,proto3" json:"pong_bool,omitempty"`
	PongString   string           `protobuf:"bytes,12,opt,name=pong_string,json=pongString,proto3" json:"pong_string,omitempty"`
	PongBytes    []byte           `protobuf:"bytes,13,opt,name=pong_bytes,json=pongBytes,proto3" json:"pong_bytes,omitempty"`
	PongFloat    float32          `protobuf:"fixed32,14,opt,name=pong_float,json=pongFloat,proto3" json:"pong_float,omitempty"`
	PongDouble   float64          `protobuf:"fixed64,15,opt,name=pong_double,json=pongDouble,proto3" json:"pong_double,omitempty"`
	PongList     []*Pong          `protobuf:"bytes,16,rep,name=pong_list,json=pongList,proto3" json:"pong_list,omitempty"`
	PongMap      map[string]*Pong `protobuf:"bytes,17,rep,name=pong_map,json=pongMap,proto3" json:"pong_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are valid to be assigned to PongOneOf:
	//
	//	*Pong_PongOneOfString
	//	*Pong_PongOneOfBool
	PongOneOf            isPong_PongOneOf `protobuf_oneof:"pong_one_of"`
	PongEnum             PongEnum         `protobuf:"varint,20,opt,name=pong_enum,json=pongEnum,proto3,enum=uber.infra.net.rpc.probe.PongEnum" json:"pong_enum,omitempty"`
	PongMessage          *Pong            `protobuf:"bytes,21,opt,name=pong_message,json=pongMessage,proto3" json:"pong_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bfd0bb539ed105e, []int{11}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

type isPong_PongOneOf interface {
	isPong_PongOneOf()
}

type Pong_PongOneOfString struct {
	PongOneOfString string `protobuf:"bytes,18,opt,name=pong_one_of_string,json=pongOneOfString,proto3,oneof" json:"pong_one_of_string,omitempty"`
}
type Pong_PongOneOfBool struct {
	PongOneOfBool bool `protobuf:"varint,19,opt,name=pong_one_of_bool,json=pongOneOfBool,proto3,oneof" json:"pong_one_of_bool,omitempty"`
}

func (*Pong_PongOneOfString) isPong_PongOneOf() {}
func (*Pong_PongOneOfBool) isPong_PongOneOf()   {}

func (m *Pong) GetPongOneOf() isPong_PongOneOf {
	if m != nil {
		return m.PongOneOf
	}
	return nil
}

func (m *Pong) GetPongInt32() int32 {
	if m != nil {
		return m.PongInt32
	}
	return 0
}

func (m *Pong) GetPongInt64() int64 {
	if m != nil {
		return m.PongInt64
	}
	return 0
}

func (m *Pong) GetPongUint32() uint32 {
	if m != nil {
		return m.PongUint32
	}
	return 0
}

func (m *Pong) GetPongUint64() uint64 {
	if m != nil {
		return m.PongUint64
	}
	return 0
}

func (m *Pong) GetPongSint32() int32 {
	if m != nil {
		return m.PongSint32
	}
	return 0
}

func (m *Pong) GetPongSint64() int64 {
	if m != nil {
		return m.PongSint64
	}
	return 0
}

func (m *Pong) GetPongFixed32() uint32 {
	if m != nil {
		return m.PongFixed32
	}
	return 0
}

func (m *Pong) GetPongFixed64() uint64 {
	if m != nil {
		return m.PongFixed64
	}
	return 0
}

func (m *Pong) GetPongSfixed32() int32 {
	if m != nil {
		return m.PongSfixed32
	}
	return 0
}

func (m *Pong) GetPongSfixed64() int64 {
	if m != nil {
		return m.PongSfixed64
	}
	return 0
}

func (m *Pong) GetPongBool() bool {
	if m != nil {
		return m.PongBool
	}
	return false
}

func (m *Pong) GetPongString() string {
	if m != nil {
		return m.PongString
	}
	return ""
}

func (m *Pong) GetPongBytes() []byte {
	if m != nil {
		return m.PongBytes
	}
	return nil
}

func (m *Pong) GetPongFloat() float32 {
	if m != nil {
		return m.PongFloat
	}
	return 0
}

func (m *Pong) GetPongDouble() float64 {
	if m != nil {
		return m.PongDouble
	}
	return 0
}

func (m *Pong) GetPongList() []*Pong {
	if m != nil {
		return m.PongList
	}
	return nil
}

func (m *Pong) GetPongMap() map[string]*Pong {
	if m != nil {
		return m.PongMap
	}
	return nil
}

func (m *Pong) GetPongOneOfString() string {
	if x, ok := m.GetPongOneOf().(*Pong_PongOneOfString); ok {
		return x.PongOneOfString
	}
	return ""
}

func (m *Pong) GetPongOneOfBool() bool {
	if x, ok := m.GetPongOneOf().(*Pong_PongOneOfBool); ok {
		return x.PongOneOfBool
	}
	return false
}

func (m *Pong) GetPongEnum() PongEnum {
	if m != nil {
		return m.PongEnum
	}
	return PongEnum_PONG_ENUM_INVALID
}

func (m *Pong) GetPongMessage() *Pong {
	if m != nil {
		return m.PongMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Pong) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Pong_PongOneOfString)(nil),
		(*Pong_PongOneOfBool)(nil),
	}
}

func init() {
	proto.RegisterEnum("uber.infra.net.rpc.probe.PingEnum", PingEnum_name, PingEnum_value)
	proto.RegisterEnum("uber.infra.net.rpc.probe.PongEnum", PongEnum_name, PongEnum_value)
	proto.RegisterType((*EchoRequest)(nil), "uber.infra.net.rpc.probe.EchoRequest")
	proto.RegisterMapType((map[string]string)(nil), "uber.infra.net.rpc.probe.EchoRequest.ExpectedApplicationHeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "uber.infra.net.rpc.probe.EchoRequest.ExpectedTransportHeadersEntry")
	proto.RegisterType((*EchoResponse)(nil), "uber.infra.net.rpc.probe.EchoResponse")
	proto.RegisterType((*EchoErrorDetail)(nil), "uber.infra.net.rpc.probe.EchoErrorDetail")
	proto.RegisterType((*EchoAnyRequest)(nil), "uber.infra.net.rpc.probe.EchoAnyRequest")
	proto.RegisterType((*EchoDurationType)(nil), "uber.infra.net.rpc.probe.EchoDurationType")
	proto.RegisterType((*EchoIntType)(nil), "uber.infra.net.rpc.probe.EchoIntType")
	proto.RegisterType((*EchoNestedType)(nil), "uber.infra.net.rpc.probe.EchoNestedType")
	proto.RegisterType((*EchoAnyResponse)(nil), "uber.infra.net.rpc.probe.EchoAnyResponse")
	proto.RegisterType((*EchoStreamRequest)(nil), "uber.infra.net.rpc.probe.EchoStreamRequest")
	proto.RegisterMapType((map[string]string)(nil), "uber.infra.net.rpc.probe.EchoStreamRequest.ExpectedApplicationHeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "uber.infra.net.rpc.probe.EchoStreamRequest.ExpectedTransportHeadersEntry")
	proto.RegisterType((*EchoStreamResponse)(nil), "uber.infra.net.rpc.probe.EchoStreamResponse")
	proto.RegisterType((*Ping)(nil), "uber.infra.net.rpc.probe.Ping")
	proto.RegisterMapType((map[string]*Ping)(nil), "uber.infra.net.rpc.probe.Ping.PingMapEntry")
	proto.RegisterType((*Pong)(nil), "uber.infra.net.rpc.probe.Pong")
	proto.RegisterMapType((map[string]*Pong)(nil), "uber.infra.net.rpc.probe.Pong.PongMapEntry")
}

func init() { proto.RegisterFile("deep_gogo.proto", fileDescriptor_9bfd0bb539ed105e) }

var fileDescriptor_9bfd0bb539ed105e = []byte{
	// 1387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x98, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0xc7, 0x4d, 0xd9, 0xf2, 0xcb, 0xfa, 0x4d, 0xde, 0x38, 0x79, 0x18, 0x3d, 0x79, 0x51, 0x55,
	0xa4, 0x50, 0x9a, 0x54, 0x2a, 0x14, 0x41, 0x08, 0x1a, 0x14, 0x85, 0x65, 0xcb, 0xb1, 0x9a, 0x58,
	0x12, 0x98, 0xa4, 0x01, 0x72, 0x61, 0x29, 0x69, 0x25, 0x13, 0xa1, 0x76, 0x58, 0x72, 0xd5, 0x84,
	0xc7, 0x9e, 0x72, 0xea, 0x27, 0xe9, 0xa9, 0x1f, 0xa0, 0xa7, 0x7e, 0x84, 0xf6, 0x03, 0x15, 0xbb,
	0x4b, 0x8a, 0xa4, 0x28, 0xd3, 0x72, 0xe2, 0x53, 0x7b, 0x31, 0xc8, 0xd9, 0x99, 0x3f, 0x67, 0x87,
	0xf3, 0x9b, 0xa5, 0x85, 0x76, 0x07, 0x84, 0xd8, 0xfa, 0x08, 0x46, 0x50, 0xb6, 0x1d, 0x60, 0x80,
	0xd5, 0x49, 0x8f, 0x38, 0x65, 0x93, 0x0e, 0x1d, 0xa3, 0x4c, 0x09, 0x2b, 0x3b, 0x76, 0x9f, 0xaf,
	0xf4, 0x48, 0xfe, 0xce, 0x08, 0x60, 0x64, 0x91, 0x8a, 0xf0, 0xeb, 0x4d, 0x86, 0x95, 0xc1, 0xc4,
	0x31, 0x98, 0x09, 0x54, 0x46, 0xe6, 0x6f, 0xce, 0xae, 0x1b, 0xd4, 0x93, 0x4b, 0xc5, 0xdf, 0xb2,
	0x68, 0xb3, 0xd9, 0x3f, 0x03, 0x8d, 0xfc, 0x34, 0x21, 0x2e, 0xc3, 0x8f, 0xd1, 0x9a, 0x6d, 0x78,
	0x16, 0x18, 0x03, 0x55, 0x29, 0x28, 0xa5, 0xcd, 0xea, 0x9d, 0xf2, 0x79, 0x8f, 0x2d, 0x77, 0x4d,
	0x3a, 0xd2, 0x02, 0x77, 0xdc, 0x44, 0x7b, 0xae, 0xc5, 0x53, 0xee, 0x91, 0x21, 0x38, 0x44, 0xef,
	0x83, 0xed, 0xa9, 0x19, 0xa1, 0x71, 0xb3, 0x2c, 0x13, 0x28, 0x07, 0x09, 0x94, 0x8f, 0xfc, 0x04,
	0xb5, 0x5d, 0x11, 0xd3, 0x10, 0x21, 0x87, 0x60, 0x7b, 0xf8, 0x10, 0xe5, 0xa4, 0x8c, 0x31, 0x64,
	0xc4, 0x91, 0x2a, 0xcb, 0x17, 0xa9, 0xec, 0x88, 0x90, 0x03, 0x1e, 0x21, 0x44, 0x1e, 0x22, 0xec,
	0x10, 0xd7, 0x06, 0x3a, 0xd0, 0xdf, 0x99, 0xec, 0x4c, 0x27, 0x8e, 0x03, 0x8e, 0xba, 0x52, 0x50,
	0x4a, 0xeb, 0x5a, 0xce, 0x5f, 0x79, 0x6d, 0xb2, 0xb3, 0x26, 0xb7, 0xe3, 0x5f, 0x14, 0x94, 0x27,
	0xef, 0x6d, 0xd2, 0x67, 0x64, 0xa0, 0x33, 0xc7, 0xa0, 0xae, 0x0d, 0x0e, 0xd3, 0xcf, 0x88, 0x31,
	0x20, 0x8e, 0xab, 0x66, 0x0b, 0xcb, 0xa5, 0xcd, 0xea, 0xe1, 0xf9, 0x75, 0x88, 0xd4, 0xaf, 0xdc,
	0xf4, 0x75, 0x5e, 0x06, 0x32, 0x27, 0x52, 0xa5, 0x49, 0x99, 0xe3, 0x69, 0x2a, 0x39, 0x67, 0x19,
	0x7f, 0x50, 0xd0, 0xad, 0x69, 0x0e, 0x86, 0x6d, 0x5b, 0x66, 0x5f, 0x6c, 0x6d, 0x9a, 0xc5, 0xaa,
	0xc8, 0xa2, 0x79, 0xb9, 0x2c, 0x0e, 0x42, 0xa1, 0x58, 0x1e, 0xd3, 0xed, 0x26, 0x1d, 0xf2, 0xcf,
	0xd0, 0xed, 0xd4, 0x4d, 0xe0, 0x1c, 0x5a, 0x7e, 0x4b, 0x3c, 0xd1, 0x1e, 0x1b, 0x1a, 0xbf, 0xc4,
	0xfb, 0x28, 0xfb, 0xb3, 0x61, 0x4d, 0x88, 0x78, 0xdd, 0x1b, 0x9a, 0xbc, 0xf9, 0x26, 0xf3, 0x58,
	0xc9, 0x9f, 0xa2, 0xbb, 0x17, 0xe4, 0x72, 0x19, 0xb9, 0xe2, 0x09, 0xda, 0x92, 0xdb, 0xe4, 0x6f,
	0xd0, 0x25, 0x97, 0xeb, 0x56, 0x88, 0x74, 0x6b, 0xf1, 0x19, 0xda, 0xe5, 0x4a, 0xa2, 0x01, 0x8e,
	0x08, 0x33, 0x4c, 0xeb, 0x13, 0xc4, 0xfe, 0xca, 0xa0, 0x1d, 0xae, 0x76, 0x40, 0xbd, 0x80, 0xa3,
	0x53, 0xa4, 0x1a, 0xd4, 0x93, 0xdd, 0xf7, 0x8e, 0x58, 0xd6, 0x5b, 0x0a, 0xef, 0xa8, 0x3e, 0x34,
	0x89, 0x15, 0xa8, 0xef, 0x27, 0xda, 0x99, 0x87, 0x5f, 0x37, 0xa8, 0xc7, 0x3b, 0xf3, 0x75, 0x10,
	0x73, 0xcc, 0x43, 0xf0, 0x4b, 0x74, 0x6b, 0x2a, 0x47, 0xfa, 0x67, 0xa0, 0x07, 0x84, 0xfb, 0x92,
	0x99, 0x14, 0x49, 0xd5, 0x97, 0xe4, 0x19, 0x06, 0xc4, 0x48, 0xd5, 0xef, 0xd1, 0xff, 0xe2, 0xaa,
	0x26, 0x65, 0xbe, 0xe0, 0x72, 0x8a, 0xe0, 0xb5, 0x88, 0x60, 0x8b, 0x32, 0xa9, 0xd5, 0x45, 0xf9,
	0xb8, 0x16, 0x25, 0x2e, 0xef, 0x65, 0x29, 0xb7, 0x92, 0x22, 0x77, 0x23, 0x22, 0xd7, 0x16, 0x41,
	0x42, 0xb1, 0x78, 0x88, 0x72, 0xd1, 0x94, 0x5f, 0x7a, 0x36, 0xc1, 0x15, 0x94, 0x8d, 0xd6, 0x30,
	0x65, 0x24, 0x48, 0xbf, 0xe2, 0x13, 0x39, 0xde, 0x5a, 0x94, 0x89, 0xf8, 0x7d, 0x1e, 0xef, 0xb8,
	0x4c, 0xc4, 0x67, 0x35, 0x79, 0x83, 0x6f, 0xa0, 0x55, 0x97, 0xf4, 0x81, 0xca, 0x3a, 0x2e, 0x6b,
	0xfe, 0x5d, 0xd1, 0x94, 0xaf, 0x55, 0x26, 0x25, 0xe2, 0xd5, 0x78, 0x8f, 0x6c, 0x84, 0xe3, 0xef,
	0x5b, 0xb4, 0x2a, 0x77, 0xec, 0xbf, 0x8b, 0x7b, 0xe9, 0xa4, 0xfa, 0x09, 0x69, 0x7e, 0x50, 0xf1,
	0xef, 0x8c, 0x6c, 0x48, 0xd1, 0x42, 0x7e, 0x77, 0xa7, 0xf5, 0x50, 0xf6, 0xea, 0x7b, 0x68, 0xf5,
	0xaa, 0x7b, 0x68, 0xed, 0x6a, 0x7b, 0x68, 0xfd, 0x23, 0x7a, 0xe8, 0x8f, 0x2c, 0xda, 0xe3, 0xb6,
	0x17, 0xcc, 0x21, 0xc6, 0xf8, 0xbf, 0x7c, 0xc8, 0x7d, 0x58, 0xe4, 0x90, 0x6b, 0xa5, 0x37, 0x6d,
	0xac, 0x8a, 0x1f, 0x7d, 0xd4, 0xfd, 0xba, 0xd8, 0x51, 0xf7, 0xec, 0x63, 0x72, 0xf9, 0xb7, 0x1d,
	0x78, 0x6d, 0x84, 0xa3, 0x9b, 0xfd, 0xe4, 0x63, 0xef, 0xcf, 0x35, 0xb4, 0xc2, 0x3b, 0x1a, 0xdf,
	0x46, 0xc8, 0x36, 0xe9, 0x88, 0xd3, 0xfa, 0xa8, 0xea, 0x4f, 0xc3, 0x0d, 0x6e, 0x69, 0x71, 0x43,
	0x74, 0xb9, 0x5e, 0xf3, 0xa7, 0x62, 0xb0, 0x5c, 0xaf, 0xe1, 0xbb, 0x68, 0x53, 0x2c, 0x4f, 0x64,
	0x38, 0x6f, 0xdd, 0x6d, 0x4d, 0x44, 0xbc, 0x12, 0x96, 0x98, 0x43, 0xbd, 0x26, 0x9a, 0x72, 0x25,
	0x74, 0x88, 0x28, 0xb8, 0x52, 0x81, 0x8f, 0xb3, 0x3d, 0xe9, 0xf0, 0x22, 0xae, 0xe0, 0x4a, 0x05,
	0x3e, 0x9c, 0x70, 0xe8, 0x50, 0xaf, 0xe1, 0xcf, 0xd0, 0x96, 0x70, 0x18, 0x9a, 0xef, 0xc9, 0xe0,
	0x51, 0x55, 0x4c, 0x9b, 0x35, 0x4d, 0x04, 0x1d, 0x4b, 0x53, 0xdc, 0xa5, 0x5e, 0x13, 0x13, 0x64,
	0x35, 0xe2, 0x52, 0xaf, 0xe1, 0xcf, 0xd1, 0xb6, 0x7c, 0x4c, 0x20, 0xb3, 0x51, 0x50, 0x4a, 0xbb,
	0x9a, 0x88, 0x7b, 0xe1, 0xdb, 0x66, 0x9c, 0xea, 0x35, 0x15, 0x15, 0x94, 0x52, 0x2e, 0xea, 0x54,
	0xaf, 0xe1, 0xff, 0x23, 0x51, 0x20, 0xbd, 0x07, 0x60, 0xa9, 0x9b, 0x82, 0xc2, 0x75, 0x6e, 0x68,
	0x00, 0x58, 0xe1, 0x6e, 0x98, 0x63, 0xd2, 0x91, 0xba, 0x25, 0xde, 0xb3, 0xdc, 0x8d, 0xb0, 0x4c,
	0x0b, 0xde, 0xf3, 0x18, 0x71, 0xd5, 0xed, 0x82, 0x52, 0xda, 0x92, 0x05, 0x6f, 0x70, 0xc3, 0x74,
	0x79, 0x68, 0x81, 0xc1, 0xd4, 0x9d, 0x82, 0x52, 0xca, 0xc8, 0xe5, 0x63, 0x6e, 0x98, 0xca, 0x0f,
	0x60, 0xd2, 0xb3, 0x88, 0xba, 0x5b, 0x50, 0x4a, 0x8a, 0x94, 0x3f, 0x12, 0x16, 0xfc, 0xc4, 0x4f,
	0xce, 0x32, 0x5d, 0xa6, 0xe6, 0x04, 0x5f, 0x17, 0xcd, 0x3c, 0x91, 0xfc, 0x73, 0xd3, 0x65, 0xf8,
	0x18, 0x89, 0x6b, 0x7d, 0x6c, 0xd8, 0xea, 0x9e, 0x88, 0x7d, 0x90, 0x1e, 0x2b, 0xfe, 0x9c, 0x1a,
	0xb6, 0x64, 0x6f, 0xcd, 0x96, 0x77, 0xf8, 0x2b, 0x84, 0x85, 0x0e, 0x50, 0xa2, 0xc3, 0x30, 0xa8,
	0x05, 0xe6, 0xb5, 0x38, 0x59, 0xd2, 0x76, 0xf9, 0x5a, 0x87, 0x92, 0xce, 0xd0, 0x2f, 0xc9, 0x7d,
	0x94, 0x8b, 0xba, 0x8b, 0xba, 0x5e, 0xe3, 0x75, 0x3d, 0x59, 0xd2, 0xb6, 0xa7, 0xce, 0xa2, 0xbc,
	0xdf, 0xf9, 0xdb, 0x23, 0x74, 0x32, 0x56, 0xf7, 0x0b, 0x4a, 0x69, 0xa7, 0x5a, 0x4c, 0x4f, 0xb1,
	0x49, 0x27, 0x63, 0xb9, 0x45, 0x7e, 0x85, 0x0f, 0xfc, 0x4e, 0x19, 0x13, 0xd7, 0x35, 0x46, 0x44,
	0xbd, 0xbe, 0xd0, 0xb1, 0x20, 0x8a, 0x7e, 0x2a, 0x43, 0xf2, 0x6f, 0xd0, 0x56, 0x74, 0xdb, 0x73,
	0x30, 0xaf, 0x45, 0x31, 0xbf, 0x58, 0x3d, 0x1c, 0x03, 0x8d, 0x6d, 0xff, 0xfd, 0xca, 0x52, 0x48,
	0x8a, 0xc1, 0xef, 0x1a, 0x48, 0x50, 0x0c, 0x51, 0x8a, 0x21, 0x41, 0x31, 0x44, 0x29, 0x86, 0x24,
	0xc5, 0x10, 0xa3, 0x18, 0x92, 0x14, 0x43, 0x8c, 0x62, 0x48, 0x52, 0x0c, 0x31, 0x8a, 0x21, 0x49,
	0x31, 0xc4, 0x28, 0x86, 0x39, 0x14, 0x43, 0x9c, 0x62, 0x98, 0x43, 0x31, 0xc4, 0x29, 0x86, 0x79,
	0x14, 0xc3, 0x0c, 0xc5, 0x30, 0x8f, 0x62, 0x98, 0xa1, 0x18, 0x66, 0x29, 0x86, 0x08, 0xc5, 0x90,
	0xa4, 0x18, 0x62, 0x14, 0x43, 0x82, 0x62, 0x88, 0x52, 0x0c, 0x09, 0x8a, 0x21, 0x4a, 0x31, 0x24,
	0x29, 0x86, 0x18, 0xc5, 0xb0, 0x38, 0xc5, 0x20, 0x28, 0x86, 0x08, 0xc5, 0xb0, 0x30, 0xc5, 0xc0,
	0x29, 0x86, 0x18, 0xc5, 0x10, 0x52, 0x0c, 0x29, 0x14, 0x43, 0x92, 0x62, 0x38, 0x97, 0x62, 0x98,
	0xa5, 0x18, 0x16, 0xa7, 0x18, 0xa6, 0x14, 0x43, 0x84, 0x62, 0xb8, 0x14, 0xc5, 0x20, 0x28, 0x86,
	0x38, 0xc5, 0x70, 0x55, 0x14, 0x43, 0x92, 0xe2, 0xb0, 0x14, 0x5f, 0xb6, 0xd0, 0x7a, 0x30, 0x89,
	0xf0, 0x75, 0xb4, 0xd7, 0x6d, 0xb5, 0x9f, 0xea, 0xcd, 0xf6, 0xab, 0x53, 0xbd, 0xd5, 0xfe, 0xe1,
	0xe0, 0x79, 0xeb, 0x28, 0xb7, 0x84, 0x31, 0xda, 0x09, 0xcd, 0xfc, 0x2a, 0xa7, 0xcc, 0xd8, 0x3a,
	0xed, 0xa7, 0xb9, 0x8c, 0x90, 0x82, 0x88, 0x54, 0x67, 0xbe, 0x54, 0x67, 0x8e, 0x54, 0x27, 0x2e,
	0x55, 0xfd, 0x3d, 0x83, 0xb2, 0x5d, 0x9e, 0x3e, 0x7e, 0x8d, 0x56, 0xf8, 0xb7, 0x07, 0xbe, 0xb7,
	0xd0, 0x6f, 0x0e, 0xf9, 0x2f, 0x2e, 0x72, 0x93, 0x1f, 0x2f, 0xc5, 0x25, 0xfc, 0x23, 0x5a, 0xf3,
	0xff, 0xd5, 0xc1, 0xa5, 0xf4, 0xa0, 0xf0, 0x1f, 0xea, 0xfc, 0xfd, 0x05, 0x3c, 0xa7, 0x4f, 0x18,
	0x23, 0x14, 0x7e, 0x36, 0xe1, 0x07, 0x97, 0xf8, 0x92, 0xcc, 0x3f, 0x5c, 0xcc, 0x39, 0x78, 0x54,
	0x49, 0xf9, 0x5a, 0x69, 0x98, 0xe8, 0x56, 0x1f, 0xc6, 0xe7, 0x06, 0x36, 0x90, 0x28, 0x68, 0x97,
	0x7f, 0xd1, 0x77, 0x95, 0x37, 0x4f, 0x46, 0x20, 0x5d, 0xc1, 0x19, 0x55, 0x3c, 0xc3, 0xb1, 0xfb,
	0x15, 0x42, 0xfb, 0x30, 0x30, 0xe9, 0x28, 0xfc, 0x85, 0xce, 0xa4, 0x8c, 0x38, 0xd4, 0xb0, 0x2a,
	0x8c, 0xb8, 0xcc, 0xee, 0x55, 0x84, 0x90, 0xdd, 0xeb, 0xad, 0x0a, 0x8f, 0x47, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xb4, 0xd4, 0x18, 0xa9, 0x1e, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProbeClient is the client API for Probe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProbeClient interface {
	// Echo procedure copies the EchoRequest and returns back the same as EchoResponse
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// EchoAny procedure parse and copies the proto.any fields from EchoAnyRequest
	// and returns back to EchoAnyResponse
	EchoAny(ctx context.Context, in *EchoAnyRequest, opts ...grpc.CallOption) (*EchoAnyResponse, error)
	// EchoStream procedure copies EchoStreamRequest and returns back as EchoStreamResponse to the stream
	EchoStream(ctx context.Context, opts ...grpc.CallOption) (Probe_EchoStreamClient, error)
}

type probeClient struct {
	cc *grpc.ClientConn
}

func NewProbeClient(cc *grpc.ClientConn) ProbeClient {
	return &probeClient{cc}
}

func (c *probeClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/uber.infra.net.rpc.probe.Probe/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeClient) EchoAny(ctx context.Context, in *EchoAnyRequest, opts ...grpc.CallOption) (*EchoAnyResponse, error) {
	out := new(EchoAnyResponse)
	err := c.cc.Invoke(ctx, "/uber.infra.net.rpc.probe.Probe/EchoAny", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeClient) EchoStream(ctx context.Context, opts ...grpc.CallOption) (Probe_EchoStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Probe_serviceDesc.Streams[0], "/uber.infra.net.rpc.probe.Probe/EchoStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &probeEchoStreamClient{stream}
	return x, nil
}

type Probe_EchoStreamClient interface {
	Send(*EchoStreamRequest) error
	Recv() (*EchoStreamResponse, error)
	grpc.ClientStream
}

type probeEchoStreamClient struct {
	grpc.ClientStream
}

func (x *probeEchoStreamClient) Send(m *EchoStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *probeEchoStreamClient) Recv() (*EchoStreamResponse, error) {
	m := new(EchoStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProbeServer is the server API for Probe service.
type ProbeServer interface {
	// Echo procedure copies the EchoRequest and returns back the same as EchoResponse
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// EchoAny procedure parse and copies the proto.any fields from EchoAnyRequest
	// and returns back to EchoAnyResponse
	EchoAny(context.Context, *EchoAnyRequest) (*EchoAnyResponse, error)
	// EchoStream procedure copies EchoStreamRequest and returns back as EchoStreamResponse to the stream
	EchoStream(Probe_EchoStreamServer) error
}

// UnimplementedProbeServer can be embedded to have forward compatible implementations.
type UnimplementedProbeServer struct {
}

func (*UnimplementedProbeServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedProbeServer) EchoAny(ctx context.Context, req *EchoAnyRequest) (*EchoAnyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoAny not implemented")
}
func (*UnimplementedProbeServer) EchoStream(srv Probe_EchoStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EchoStream not implemented")
}

func RegisterProbeServer(s *grpc.Server, srv ProbeServer) {
	s.RegisterService(&_Probe_serviceDesc, srv)
}

func _Probe_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uber.infra.net.rpc.probe.Probe/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Probe_EchoAny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoAnyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServer).EchoAny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uber.infra.net.rpc.probe.Probe/EchoAny",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServer).EchoAny(ctx, req.(*EchoAnyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Probe_EchoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProbeServer).EchoStream(&probeEchoStreamServer{stream})
}

type Probe_EchoStreamServer interface {
	Send(*EchoStreamResponse) error
	Recv() (*EchoStreamRequest, error)
	grpc.ServerStream
}

type probeEchoStreamServer struct {
	grpc.ServerStream
}

func (x *probeEchoStreamServer) Send(m *EchoStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *probeEchoStreamServer) Recv() (*EchoStreamRequest, error) {
	m := new(EchoStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Probe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uber.infra.net.rpc.probe.Probe",
	HandlerType: (*ProbeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Probe_Echo_Handler,
		},
		{
			MethodName: "EchoAny",
			Handler:    _Probe_EchoAny_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EchoStream",
			Handler:       _Probe_EchoStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "deep_gogo.proto",
}
